/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.steam.ui;

import com.steam.model.Game;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.text.SimpleDateFormat;

/**
 *
 * @author Toyo
 */
public class GameInGenre extends javax.swing.JPanel {

    /**
     * Creates new form GameInGenre
     */
    public GameInGenre(Game game) {
        initComponents();
        //setPreferredSize(new Dimension(800, 150)); 
        jLabel9.setVisible(false);
        setScaleImage(jLabel111, "/game"+game.getId()+"/header.jpg");
        lblGameNameInStore1.setText(game.getName());
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        lblReleaseDate.setText(sdf.format(game.getReleaseDate()));
        lblPriceGame1.setText(Double.toString(game.getPrice()));
    }
    
    private void setScaleImage(JLabel objectName, String path){
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        // Lấy kích thước thực tế của JLabel
        int width = objectName.getWidth();
        int height = objectName.getHeight();

        if (width == 0){
            width = 200;
        }
        if (height == 0){
            height= 105;
        }
        // Co ảnh lại cho vừa khung
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(img);
        scaledIcon.setDescription(path); // 🔹 Lưu lại đường dẫn
        objectName.setIcon(null);
        objectName.setIcon(scaledIcon);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel111 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblGameNameInStore1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblReleaseDate = new javax.swing.JLabel();
        lblPriceGame1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 21, 40));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jLabel111.setText("jLabel1");
        jLabel111.setPreferredSize(new java.awt.Dimension(200, 105));
        jPanel1.add(jLabel111);

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(0, 21, 40));

        lblGameNameInStore1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGameNameInStore1.setForeground(new java.awt.Color(255, 255, 255));
        lblGameNameInStore1.setText("Grand Theft Auto V");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tag");

        lblReleaseDate.setForeground(new java.awt.Color(255, 255, 255));
        lblReleaseDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReleaseDate.setText("ngày phát hành");
        lblReleaseDate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblPriceGame1.setForeground(new java.awt.Color(255, 255, 255));
        lblPriceGame1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceGame1.setText("Giá tiền");
        lblPriceGame1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lblGameNameInStore1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReleaseDate)
                    .addComponent(lblPriceGame1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGameNameInStore1)
                    .addComponent(lblPriceGame1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblReleaseDate))
                .addGap(15, 15, 15))
        );

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblGameNameInStore1;
    private javax.swing.JLabel lblPriceGame1;
    private javax.swing.JLabel lblReleaseDate;
    // End of variables declaration//GEN-END:variables
}
