/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.steam.ui;

import com.steam.model.User;
import com.steam.repository.UserRepository;
import com.steam.repository.impl.UserRepositoryImpl;
import com.steam.service.UserService;
import com.steam.service.impl.UserServiceImpl;
import com.steam.util.DBConnection;
import com.steam.util.RandomCode;
import com.steam.util.SendVerification;
import java.sql.Connection;
import java.util.concurrent.ExecutionException;

import javax.swing.*;
/**
 *
 * @author Admin
 */
public class RecoverAccount extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RecoverAccount.class.getName());
    private static final UserRepository userRepository = new UserRepositoryImpl();
    private String oldInputEmail = "";
    private User getUser;
    /**
     * Creates new form RecoverAccount
     */
    public RecoverAccount(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblAnc.setVisible(false);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        butExcute = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JTextField();
        lblAnc = new javax.swing.JLabel();
        butExcute1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 49, 96));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(28, 32, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập tài khoản email:");

        butExcute.setText("Tiếp tục");
        butExcute.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butExcute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExcuteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhập mật khẩu mới:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập lại mật khẩu mới:");

        lblAnc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblAnc.setForeground(new java.awt.Color(255, 255, 255));
        lblAnc.setText("Tai khoan khong ton tai");

        butExcute1.setText("Quay lại");
        butExcute1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        butExcute1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butExcute1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblAnc)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(butExcute1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addComponent(butExcute, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnc, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butExcute, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butExcute1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butExcuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExcuteActionPerformed
        // TODO add your handling code here:
        
        if (txtEmail.getText().trim().isEmpty() || txtPassword.getText().trim().isEmpty() || txtPassword2.getText().trim().isEmpty()){
            lblAnc.setText("Vui lòng nhập đủ thông tin");
            lblAnc.setVisible(true);
            return;
        }
        if (oldInputEmail.isEmpty()){
            oldInputEmail = txtEmail.getText().trim();
            getUser = userRepository.findByEmail(txtEmail.getText().trim());
        }
        else if (!oldInputEmail.equals(txtEmail.getText().trim())){
            getUser = userRepository.findByEmail(txtEmail.getText().trim());
        }

        if (getUser == null){
            lblAnc.setText("Tài khoản không tồn tại");
            lblAnc.setVisible(true);
            return;
        }
        if (!txtPassword.getText().trim().equals(txtPassword2.getText().trim())){
            lblAnc.setText("Hai mật khẩu không trùng khớp");
            lblAnc.setVisible(true);
            return;
        }
        String code = RandomCode.generateConfirmCode();
        SendVerification de = new SendVerification();
        de.sendVerificationCode(txtEmail.getText().trim(), code);
        String name = JOptionPane.showInputDialog(this, "Một mã code đã được gửi tới " + txtEmail.getText().toString().trim() + ". Vui lòng nhập code để hoàn tất việc đổi mật khẩu", "Finish change password", JOptionPane.QUESTION_MESSAGE);
        if (name.trim().equals(code)){
                // suy nghi ve viec nen giu mat khau cu hoac khong vi ?
                String oldPassword = getUser.getPassWord();
                getUser.setPassWord(txtPassword.getText().trim());
                //System.out.println(txtPassword.toString().trim());
                User updateStatus = userRepository.updateUser(getUser);
                if (updateStatus == null){
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi", "Show Message Dialog", JOptionPane.ERROR_MESSAGE);
                    getUser.setPassWord(oldPassword);
                    return;
                }
                JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công", "Show Message Dialog", JOptionPane.INFORMATION_MESSAGE);
                dispose();
                //User user = userService.registerUser(userInfo);
                //new MainMenu(userInfo).setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Code không hợp lệ", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
        }
        
    }//GEN-LAST:event_butExcuteActionPerformed

    private void butExcute1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butExcute1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_butExcute1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                RecoverAccount dialog = new RecoverAccount(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butExcute;
    private javax.swing.JButton butExcute1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPassword2;
    // End of variables declaration//GEN-END:variables
}
