/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.steam.ui;

import java.awt.Dimension;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.Border;

/**
 *
 * @author Toyo
 */
public class Test3 extends javax.swing.JPanel {

    /**
     * Creates new form Test3
     */
    public Test3(String name, String path) {
        initComponents();
        jLabel2.setText("");
        jLabel2.setText(name);
        setScaleImage(jLabel1, path);
        jLabel2.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 0));
        //setPreferredSize(new Dimension(300, 50)); // Điều chỉnh size phù hợp
        //setMinimumSize(new Dimension(200, 50));
        //setMaximumSize(new Dimension(Integer.MAX_VALUE, 50));
        
    }

    private void setScaleImage(JLabel objectName, String path){
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        // Lấy kích thước thực tế của JLabel
        
        int width = objectName.getWidth();
        int height = objectName.getHeight();

        if (width == 0){
            width = 65;
        }
        if (height == 0){
            height= 40;
        }
        // Co ảnh lại cho vừa khung
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(img);
        scaledIcon.setDescription(path); // 🔹 Lưu lại đường dẫn
        objectName.setIcon(null);
        objectName.setIcon(scaledIcon);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(36, 40, 47));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
